title: Huang Huan's CV (Data Scientist/Bioinformatician)
description: Huang is his family name in Chinese culture, and Huan is his given name.
url: https://coolandhot.github.io/cv-ver2/
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
